export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCESS="FETCH_DATA_SUCESS";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE"; 

export const GET_SINGLE_PRODUCT_REQUEST="GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCESS="GET_SINGLE_PRODUCT_SUCESS"
export const GET_SINGLE_PRODUCT_FAILURE="GET_SINGLE_PRODUCT_FAILURE"